"""Contratos públicos de triaje."""

from .catalogs import Category, CatalogsResponse, Department, Provider, Urgency
from .errors import ErrorCode, ErrorDetail, ErrorResponse
from .health import HealthResponse, ServiceHealth, ServiceId, ServiceStatus
from .knowledge import (
    KnowledgeBase,
    KnowledgeBaseSummary,
    KnowledgeDocument,
    KnowledgeEvidence,
    KnowledgeSourceSummary,
)
from .metrics import (
    ComparisonProviderResult,
    ComparisonRequest,
    ComparisonReviewRecord,
    ComparisonReviewRequest,
    ComparisonResponse,
    EvaluationCase,
    EvaluationDataset,
    EvaluationObservation,
    EvaluationReport,
    ExecutionMetrics,
    MetricsSummary,
    PricingReference,
    ProviderMetricsSummary,
    ProviderEvaluationSummary,
)
from .privacy import PrivacyMetadata, PrivacyResult, RedactionType
from .risk_matrix import (
    RiskMatrixDocument,
    RiskMatrixObservation,
    RiskMatrixQuery,
    RiskMatrixRule,
)
from .similarity import (
    NoticeEmbedding,
    SimilarityMatch,
    SimilarityResult,
    StoredNoticeEmbedding,
)
from .triage import TriageRequest, TriageResult
from .workflow import (
    AuditEventRecord,
    ClassificationDecision,
    NoticeRecord,
    NoticePage,
    ProposalStatus,
    ReviewDecision,
    ReviewRecord,
    ReviewRequest,
    ReviewResponse,
    TriageProposalResponse,
    TriageRunRecord,
)

__all__ = [
    "AuditEventRecord",
    "CatalogsResponse",
    "Category",
    "ClassificationDecision",
    "ComparisonProviderResult",
    "ComparisonRequest",
    "ComparisonReviewRecord",
    "ComparisonReviewRequest",
    "ComparisonResponse",
    "ErrorDetail",
    "ErrorCode",
    "ErrorResponse",
    "Department",
    "EvaluationCase",
    "EvaluationDataset",
    "EvaluationObservation",
    "EvaluationReport",
    "ExecutionMetrics",
    "HealthResponse",
    "KnowledgeBase",
    "KnowledgeBaseSummary",
    "KnowledgeDocument",
    "KnowledgeEvidence",
    "KnowledgeSourceSummary",
    "NoticeRecord",
    "NoticeEmbedding",
    "NoticePage",
    "MetricsSummary",
    "ProposalStatus",
    "PricingReference",
    "PrivacyMetadata",
    "PrivacyResult",
    "Provider",
    "ProviderMetricsSummary",
    "ProviderEvaluationSummary",
    "ReviewDecision",
    "ReviewRecord",
    "ReviewRequest",
    "ReviewResponse",
    "RedactionType",
    "RiskMatrixDocument",
    "RiskMatrixObservation",
    "RiskMatrixQuery",
    "RiskMatrixRule",
    "ServiceHealth",
    "ServiceId",
    "ServiceStatus",
    "SimilarityMatch",
    "SimilarityResult",
    "StoredNoticeEmbedding",
    "TriageProposalResponse",
    "TriageRequest",
    "TriageResult",
    "TriageRunRecord",
    "Urgency",
]
